### ISSUE TITLE
Property [id] does not exist on this collection instance.

### ISSUE THREAD

**Issue by eiiot** [doefom/restrict#6]
https://flareapp.io/share/Lm8KLbj5

I get the above error when viewing`/cp/collections/articles`.

**Comment by doefom** [comment]
Hello @eiiot, thanks for reaching out. Can you share the blueprint and the contents of the entry for which the error occurs?

**Comment by eiiot** [comment]
I'm not sure which entry the error occurs for, sadly.

Here's the blueprint:


```yaml
title: Article
tabs:
  main:
    display: Main
    sections:
      - fields:
          - handle: title
            field:
              type: text
              required: true
              validate:
                - required
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
          - handle: subheadline
            field:
              antlers: false
              type: textarea
              display: Subheadline
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          - handle: content
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Content
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      - display: Editing
        fields:
          - handle: linked_google_doc
            field:
              type: linked_google_doc
              display: "Linked Google Doc"
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          - handle: first_copied_by
            field:
              mode: select
              query_scopes:
                - editor_scope
              type: users
              display: "First Copied By"
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          - handle: second_copied_by
            field:
              mode: select
              query_scopes:
                - editor_scope
              type: users
              display: "Second Copied By"
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              if:
                first_copied_by: "not empty"
  sidebar:
    display: Sidebar
    sections:
      - fields:
          - handle: slug
            field:
              type: slug
              localizable: true
              validate: "max:200"
          - handle: date
            field:
              type: date
              required: true
              default: now
              validate:
                - required
          - handle: author
            field:
              type: users
              display: Author
              localizable: true
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              mode: select
              query_scopes:
                - writer_scope
              hide_display: false
              validate:
                - required
          - handle: editors
            field:
              type: users
              display: Editors
              localizable: true
              default: current
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              mode: select
              query_scopes:
                - editor_scope
              hide_display: false
              validate:
                - required
      - display: Media
        fields:
          - handle: featured_image
            field:
              max_files: 1
              mode: grid
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: "Featured Image"
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      - display: Metadata
        fields:
          - handle: section
            field:
              max_items: 1
              mode: select
              create: true
              taxonomies:
                - sections
              type: terms
              display: Section
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          - handle: tags
            field:
              mode: default
              create: true
              type: terms
              display: Tags
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          - handle: excerpt
            field:
              antlers: false
              type: textarea
              display: Excerpt
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      - display: Design
        fields:
          - handle: header_layout
            field:
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: "Header Layout"
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          - handle: hide_elements
            field:
              inline: false
              type: checkboxes
              display: "Hide Elements"
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          - handle: custom_html
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: "Custom HTML"
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              always_save: false
          - handle: drop_caps
            field:
              default: false
              type: toggle
              display: "Drop Caps"
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          - handle: template
            field:
              type: template
              display: Template
              localizable: true

```
